# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9eae5e0b701f5a8229594fef1a685c0476dc146bc2b8234c79061ac51c2dea81967e399979f97f8488f397e200e39c5c43c5ff508dff60919f5b4f1f53c7212

test:
  secret_key_base: e6a2db61ec92395e6c94fddd731c50ada12f0d64416e178508c95c9e8383b4081e1cca89aca147936034e4e1c928d45a08ba17a746d9c78d2536ab9ede0032c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
